import type { Design } from './store';
import { materialById } from './store';
import { creaseSegment, netMetrics, panelPoly, type Net } from './geometry';
import { drawArtwork, drawDieline, preloadAll } from './render2d';
import { chooseSheet, type SheetChoice } from './sheets';

/**
 * True when the studio is running inside an iframe. Embedded previews are
 * usually sandboxed without `allow-downloads`, which silently swallows saves,
 * so the UI warns and offers a real tab instead of failing quietly.
 */
export const isEmbedded = (() => {
  try { return window.self !== window.top; } catch { return true; }
})();

export function download(name: string, data: string | Blob) {
  const url = typeof data === 'string' ? data : URL.createObjectURL(data);
  const a = document.createElement('a');
  a.href = url;
  a.download = name;
  a.rel = 'noopener';
  document.body.appendChild(a);
  a.click();
  a.remove();
  if (isEmbedded) {
    // last-ditch: a plain navigation sometimes survives where `download` does not
    try { window.open(url, '_blank', 'noopener'); } catch { /* sandboxed */ }
  }
  if (typeof data !== 'string') setTimeout(() => URL.revokeObjectURL(url), 20000);
}

const f = (n: number) => Math.round(n * 1000) / 1000;

/* ----------------------------- SVG dieline ----------------------------- */

export function dielineSVG(net: Net, design: Design): string {
  const b = net.bounds;
  const bleed = design.params.bleed;
  const pad = bleed + 6;
  const W = b.w + pad * 2;
  const H = b.h + pad * 2;
  const ox = -b.x + pad;
  const oy = -b.y + pad;

  const cut: string[] = [];
  const crease: string[] = [];
  for (const p of net.panels) {
    const d = panelPoly(p).map(([x, y], i) => `${i ? 'L' : 'M'}${f(x + ox)},${f(y + oy)}`).join(' ') + ' Z';
    cut.push(`<path d="${d}"/>`);
    if (p.parent) {
      const seg = creaseSegment(p, net.byId[p.parent]);
      if (seg) crease.push(`<line x1="${f(seg[0] + ox)}" y1="${f(seg[1] + oy)}" x2="${f(seg[2] + ox)}" y2="${f(seg[3] + oy)}"/>`);
    }
  }
  const labels = net.panels
    .filter((p) => Math.min(p.w, p.h) > 12)
    .map((p) => `<text x="${f(p.x + p.w / 2 + ox)}" y="${f(p.y + p.h / 2 + oy)}" font-size="${f(Math.min(5, p.w / 5))}" text-anchor="middle" dominant-baseline="middle" fill="#9aa3ad">${p.label.toUpperCase()}</text>`)
    .join('\n    ');

  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="${f(W)}mm" height="${f(H)}mm" viewBox="0 0 ${f(W)} ${f(H)}">
  <title>${design.name} — ${net.name} dieline</title>
  <desc>Generated by BoxCraft · ${design.params.L}×${design.params.W}×${design.params.H} mm · board ${design.params.caliper}mm</desc>
  <g id="Bleed" fill="none" stroke="#ff3b30" stroke-width="0.25" stroke-dasharray="3 2">
    <rect x="${f(ox + b.x - bleed)}" y="${f(oy + b.y - bleed)}" width="${f(b.w + bleed * 2)}" height="${f(b.h + bleed * 2)}"/>
  </g>
  <g id="Cut" fill="none" stroke="#111111" stroke-width="0.25" stroke-linejoin="round">
    ${cut.join('\n    ')}
  </g>
  <g id="Crease" fill="none" stroke="#0a84ff" stroke-width="0.25" stroke-dasharray="4 2.5">
    ${crease.join('\n    ')}
  </g>
  <g id="Labels" font-family="Helvetica, Arial, sans-serif">
    ${labels}
  </g>
</svg>`;
}

/* ----------------------------- raster art ----------------------------- */

export async function artworkCanvas(design: Design, net: Net, dpi = 300, withBleed = true): Promise<HTMLCanvasElement> {
  await preloadAll(design);
  const b = net.bounds;
  const bleed = withBleed ? design.params.bleed : 0;
  const mmToPx = dpi / 25.4;
  const W = (b.w + bleed * 2) * mmToPx;
  const H = (b.h + bleed * 2) * mmToPx;
  const scale = Math.min(1, 12000 / Math.max(W, H));
  const c = document.createElement('canvas');
  c.width = Math.round(W * scale);
  c.height = Math.round(H * scale);
  const ctx = c.getContext('2d')!;
  ctx.imageSmoothingQuality = 'high';
  ctx.scale(mmToPx * scale, mmToPx * scale);
  ctx.translate(-b.x + bleed, -b.y + bleed);
  drawArtwork(ctx, design, net, {});
  return c;
}

export async function exportArtworkPNG(design: Design, net: Net, dpi = 300) {
  const c = await artworkCanvas(design, net, dpi, true);
  download(`${slug(design.name)}-artwork-${dpi}dpi.png`, c.toDataURL('image/png'));
}

/* ----------------------------- PDF ----------------------------- */

/** Quarter-turn a canvas clockwise, for blanks that sit better across the sheet. */
function rotateCanvasCW(c: HTMLCanvasElement): HTMLCanvasElement {
  const out = document.createElement('canvas');
  out.width = c.height;
  out.height = c.width;
  const ctx = out.getContext('2d')!;
  ctx.translate(out.width / 2, out.height / 2);
  ctx.rotate(Math.PI / 2);
  ctx.drawImage(c, -c.width / 2, -c.height / 2);
  return out;
}

/**
 * Print-ready PDF on the selected full press sheet. The page keeps its chosen
 * dimensions (A4, Legal, custom, etc.); the complete bleed box is scaled and
 * placed using the editor's sheet adjustments before crop marks and dielines
 * are overlaid. Passing `opts.sheet` lets the UI share its live calculation.
 */
export async function exportPrintPDF(design: Design, net: Net, opts: { art: boolean; marks: boolean; dpi?: number; sheet?: SheetChoice }) {
  const b = net.bounds;
  const bleed = design.params.bleed;
  const sheet = opts.sheet ?? chooseSheet(net, design);
  if (!sheet.fits) throw new Error('There is no printable area on this sheet. Adjust its margin or offsets.');
  const { jsPDF } = await import('jspdf');
  const pdf = new jsPDF({
    unit: 'mm',
    format: [sheet.w, sheet.h],
    orientation: sheet.w >= sheet.h ? 'landscape' : 'portrait',
    compress: true,
  });

  // Bleed box size in mm, and the same box once turned onto the sheet.
  const artW = b.w + bleed * 2;
  const artH = b.h + bleed * 2;
  const boxW = (sheet.rotated ? artH : artW) * sheet.scale;
  const boxH = (sheet.rotated ? artW : artH) * sheet.scale;
  const ax = (sheet.w - boxW) / 2 + sheet.offsetX;
  const ay = (sheet.h - boxH) / 2 + sheet.offsetY;

  // net coordinates (mm, y-down) → adjusted sheet coordinates, honouring scale and rotation
  const map = (x: number, y: number): [number, number] => {
    const u = (x - b.x + bleed) * sheet.scale;
    const v = (y - b.y + bleed) * sheet.scale;
    return sheet.rotated ? [ax + (artH * sheet.scale - v), ay + u] : [ax + u, ay + v];
  };

  if (opts.art) {
    const c = await artworkCanvas(design, net, opts.dpi ?? 200, true);
    const img = sheet.rotated ? rotateCanvasCW(c) : c;
    pdf.addImage(img.toDataURL('image/jpeg', 0.94), 'JPEG', ax, ay, boxW, boxH);
  }

  if (opts.marks) {
    // bleed box
    pdf.setLineWidth(0.2);
    pdf.setDrawColor(255, 59, 48);
    pdf.setLineDashPattern([2, 1.5], 0);
    pdf.rect(ax, ay, boxW, boxH);
    pdf.setLineDashPattern([], 0);

    // cut lines
    pdf.setDrawColor(17, 17, 17);
    for (const p of net.panels) {
      const poly = panelPoly(p);
      for (let i = 0; i < poly.length; i++) {
        const a = poly[i], bb = poly[(i + 1) % poly.length];
        const [x1, y1] = map(a[0], a[1]);
        const [x2, y2] = map(bb[0], bb[1]);
        pdf.line(x1, y1, x2, y2);
      }
    }

    // crease lines
    pdf.setDrawColor(10, 132, 255);
    pdf.setLineDashPattern([3, 2], 0);
    for (const p of net.panels) {
      if (!p.parent) continue;
      const seg = creaseSegment(p, net.byId[p.parent]);
      if (!seg) continue;
      const [x1, y1] = map(seg[0], seg[1]);
      const [x2, y2] = map(seg[2], seg[3]);
      pdf.line(x1, y1, x2, y2);
    }
    pdf.setLineDashPattern([], 0);

    // crop marks at the bleed-box corners, sitting in the sheet margin
    pdf.setDrawColor(17, 17, 17);
    pdf.setLineWidth(0.2);
    const gap = 1.5, len = 3.5;
    const corners: [number, number][] = [[ax, ay], [ax + boxW, ay], [ax, ay + boxH], [ax + boxW, ay + boxH]];
    for (const [cx, cy] of corners) {
      const dx = cx === ax ? -1 : 1;
      const dy = cy === ay ? -1 : 1;
      pdf.line(cx + dx * gap, cy, cx + dx * (gap + len), cy);
      pdf.line(cx, cy + dy * gap, cx, cy + dy * (gap + len));
    }
  }

  pdf.setFontSize(6);
  pdf.setTextColor(120);
  pdf.text(
    `${design.name} · ${net.name} · ${design.params.L}×${design.params.W}×${design.params.H} mm · ${materialById(design.materialId).name} · bleed ${bleed}mm · BoxCraft`,
    Math.max(4, sheet.margin), sheet.h - 3.5,
  );
  pdf.text(
    `Sheet ${sheet.label} · ${sheet.w} × ${sheet.h} mm · scale ${(sheet.scale * 100).toFixed(1)}% · 1 up${sheet.rotated ? ' · artwork rotated 90°' : ''} · trim ${(sheet.trim * 100).toFixed(0)}%`,
    sheet.w - Math.max(4, sheet.margin), sheet.h - 3.5, { align: 'right' },
  );
  pdf.save(`${slug(design.name)}-${opts.art ? 'print' : 'dieline'}.pdf`);
}

/**
 * Full-page raster companion to the print PDF. The canvas is capped to keep
 * oversized press sheets from exhausting browser memory; PDF remains vector.
 */
export async function exportPrintPNG(design: Design, net: Net, dpi = 300, chosenSheet?: SheetChoice) {
  const sheet = chosenSheet ?? chooseSheet(net, design);
  if (!sheet.fits) throw new Error('There is no printable area on this sheet. Adjust its margin or offsets.');

  const pixelsPerMmAtDpi = dpi / 25.4;
  const rawW = sheet.w * pixelsPerMmAtDpi;
  const rawH = sheet.h * pixelsPerMmAtDpi;
  const pixelScale = Math.min(1, 12000 / Math.max(rawW, rawH), Math.sqrt(24_000_000 / (rawW * rawH)));
  const pageW = Math.max(1, Math.round(rawW * pixelScale));
  const pageH = Math.max(1, Math.round(rawH * pixelScale));
  const c = document.createElement('canvas');
  c.width = pageW;
  c.height = pageH;
  const ctx = c.getContext('2d');
  if (!ctx) throw new Error('Could not create the sheet canvas.');
  ctx.fillStyle = '#ffffff';
  ctx.fillRect(0, 0, pageW, pageH);

  const b = net.bounds;
  const bleed = design.params.bleed;
  const artW = b.w + bleed * 2;
  const artH = b.h + bleed * 2;
  const boxW = (sheet.rotated ? artH : artW) * sheet.scale;
  const boxH = (sheet.rotated ? artW : artH) * sheet.scale;
  const ax = (sheet.w - boxW) / 2 + sheet.offsetX;
  const ay = (sheet.h - boxH) / 2 + sheet.offsetY;
  const pxPerMm = pixelsPerMmAtDpi * pixelScale;

  const art = await artworkCanvas(design, net, dpi, true);
  const imageW = artW * sheet.scale * pxPerMm;
  const imageH = artH * sheet.scale * pxPerMm;
  ctx.save();
  if (sheet.rotated) {
    ctx.translate((ax + boxW / 2) * pxPerMm, (ay + boxH / 2) * pxPerMm);
    ctx.rotate(Math.PI / 2);
    ctx.drawImage(art, -imageW / 2, -imageH / 2, imageW, imageH);
  } else {
    ctx.drawImage(art, ax * pxPerMm, ay * pxPerMm, boxW * pxPerMm, boxH * pxPerMm);
  }
  ctx.restore();

  const map = (x: number, y: number): [number, number] => {
    const u = (x - b.x + bleed) * sheet.scale;
    const v = (y - b.y + bleed) * sheet.scale;
    return sheet.rotated ? [ax + (artH * sheet.scale - v), ay + u] : [ax + u, ay + v];
  };
  ctx.save();
  ctx.scale(pxPerMm, pxPerMm);
  ctx.lineWidth = 0.2;
  ctx.strokeStyle = '#ff3b30';
  ctx.setLineDash([2, 1.5]);
  ctx.strokeRect(ax, ay, boxW, boxH);
  ctx.setLineDash([]);

  ctx.strokeStyle = '#111111';
  for (const p of net.panels) {
    const poly = panelPoly(p);
    ctx.beginPath();
    poly.forEach(([x, y], i) => {
      const [sx, sy] = map(x, y);
      if (i) ctx.lineTo(sx, sy); else ctx.moveTo(sx, sy);
    });
    ctx.closePath();
    ctx.stroke();
  }

  ctx.strokeStyle = '#0a84ff';
  ctx.setLineDash([3, 2]);
  for (const p of net.panels) {
    if (!p.parent) continue;
    const seg = creaseSegment(p, net.byId[p.parent]);
    if (!seg) continue;
    const [x1, y1] = map(seg[0], seg[1]);
    const [x2, y2] = map(seg[2], seg[3]);
    ctx.beginPath(); ctx.moveTo(x1, y1); ctx.lineTo(x2, y2); ctx.stroke();
  }
  ctx.setLineDash([]);

  ctx.strokeStyle = '#111111';
  const gap = 1.5, len = 3.5;
  const corners: [number, number][] = [[ax, ay], [ax + boxW, ay], [ax, ay + boxH], [ax + boxW, ay + boxH]];
  for (const [cx, cy] of corners) {
    const dx = cx === ax ? -1 : 1;
    const dy = cy === ay ? -1 : 1;
    ctx.beginPath();
    ctx.moveTo(cx + dx * gap, cy); ctx.lineTo(cx + dx * (gap + len), cy);
    ctx.moveTo(cx, cy + dy * gap); ctx.lineTo(cx, cy + dy * (gap + len));
    ctx.stroke();
  }
  ctx.restore();

  const blob = await new Promise<Blob>((resolve, reject) => {
    c.toBlob((value) => value ? resolve(value) : reject(new Error('PNG encoding failed.')), 'image/png');
  });
  const effectiveDpi = Math.max(1, Math.round(dpi * pixelScale));
  download(`${slug(design.name)}-sheet-${effectiveDpi}dpi.png`, blob);
}

/* ----------------------------- spec sheet ----------------------------- */

export async function exportSpecSheet(design: Design, net: Net, renderPNG: string | null) {
  const m = materialById(design.materialId);
  const met = netMetrics(net, design.params, m.gsm);
  const { jsPDF } = await import('jspdf');
  const pdf = new jsPDF({ unit: 'mm', format: 'a4', compress: true });
  const P = 18;
  let y = P;

  pdf.setFillColor(17, 24, 39);
  pdf.rect(0, 0, 210, 34, 'F');
  pdf.setTextColor(255);
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(17);
  pdf.text('Packaging specification', P, 16);
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(9);
  pdf.setTextColor(180, 190, 205);
  pdf.text(`${design.name} · generated ${new Date().toLocaleDateString()} · BoxCraft`, P, 23.5);
  y = 46;

  if (renderPNG) {
    try {
      const dim = await imageSize(renderPNG);
      const maxW = 74, maxH = 62;
      const r = Math.min(maxW / dim.w, maxH / dim.h);
      const w = dim.w * r, h = dim.h * r;
      pdf.addImage(renderPNG, 'PNG', 194 - w, 40 + (maxH - h) / 2, w, h);
    } catch { /* ignore */ }
  }

  const row = (k: string, v: string) => {
    pdf.setTextColor(110);
    pdf.setFontSize(8.5);
    pdf.text(k.toUpperCase(), P, y);
    pdf.setTextColor(20);
    pdf.setFontSize(11);
    pdf.text(v, P, y + 5);
    y += 12.5;
  };
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(11);
  pdf.setTextColor(20);
  pdf.text('Structure', P, y); y += 7;
  pdf.setFont('helvetica', 'normal');
  row('Style', `${net.name}`);
  row('Internal dimensions (L × W × H)', `${design.params.L} × ${design.params.W} × ${design.params.H} mm`);
  row('Material', `${m.name} · ${m.caliper} mm caliper`);
  row('Flat sheet size', `${met.sheetW.toFixed(1)} × ${met.sheetH.toFixed(1)} mm`);
  const sheet = chooseSheet(net, design);
  row('Press sheet (1 up)', `${sheet.label} · ${sheet.w} × ${sheet.h} mm · scale ${(sheet.scale * 100).toFixed(1)}% · trim ${(sheet.trim * 100).toFixed(0)}%`);
  row('Sheet adjustment', `Margin ${sheet.margin} mm · placement X ${sheet.offsetX} / Y ${sheet.offsetY} mm`);
  row('Board area / blank', `${met.boardArea.toFixed(1)} cm²  (waste ${(met.waste * 100).toFixed(0)}%)`);
  row('Est. blank weight', `${met.weight.toFixed(1)} g`);
  row('Internal volume', `${met.volumeL.toFixed(2)} L`);
  row('Bleed / glue flap', `${design.params.bleed} mm / ${design.params.glue} mm`);
  row('Finish', design.scene.finish === 'gloss' ? 'Gloss lamination' : design.scene.finish === 'softTouch' ? 'Soft-touch lamination' : 'Matte varnish');

  // dieline thumbnail
  const c = document.createElement('canvas');
  const b = net.bounds;
  const s = Math.min(1600 / b.w, 1100 / b.h);
  c.width = Math.round(b.w * s) + 40;
  c.height = Math.round(b.h * s) + 40;
  const ctx = c.getContext('2d')!;
  ctx.fillStyle = '#fff'; ctx.fillRect(0, 0, c.width, c.height);
  ctx.translate(20, 20); ctx.scale(s, s); ctx.translate(-b.x, -b.y);
  drawDieline(ctx, net, {
    cut: '#111', crease: '#0a84ff', bleed: '#ff3b30', safe: '#8e8e93',
    lw: 0.9 / s, labels: true, showBleed: true, showSafe: false, labelSize: 4.5,
  }, design.params.bleed);
  const th = c.toDataURL('image/png');
  const tw = 174;
  const thh = (c.height / c.width) * tw;
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(11);
  pdf.text('Dieline', P, y + 2);
  pdf.addImage(th, 'PNG', P, y + 6, tw, Math.min(thh, 78));
  pdf.setFontSize(7.5);
  pdf.setTextColor(120);
  pdf.text('Solid = cut · dashed blue = crease · dashed red = bleed. Not to scale. Confirm with your converter before tooling.', P, 285);
  pdf.save(`${slug(design.name)}-spec.pdf`);
}

function imageSize(src: string): Promise<{ w: number; h: number }> {
  return new Promise((res, rej) => {
    const i = new Image();
    i.onload = () => res({ w: i.naturalWidth, h: i.naturalHeight });
    i.onerror = rej;
    i.src = src;
  });
}

/* ----------------------------- project ----------------------------- */

export function exportProject(design: Design) {
  download(`${slug(design.name)}.boxcraft.json`, new Blob([JSON.stringify(design, null, 2)], { type: 'application/json' }));
}

export function slug(s: string) {
  return (s || 'design').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 40) || 'design';
}
